// TODO: consider if it's still necessary to deal with 2/3-digit years.
[[two-digit-years]]
== Two Digit Years

The following requirements are to address the problems of ambiguity
of 2-digit years:

* Internet Protocols MUST generate four digit years in dates.

* The use of 2-digit years is deprecated. If a 2-digit year is
received, it should be accepted ONLY if an incorrect
interpretation will not cause a protocol or processing failure
(e.g. if used only for logging or tracing purposes).

* It is possible that a program using two digit years will
represent years after 1999 as three digits. This occurs if the
program simply subtracts 1900 from the year and doesn't check
the number of digits. Programs wishing to robustly deal with
dates generated by such broken software may add 1900 to three
digit years.

* It is possible that a program using two digit years will
represent years after 1999 as ":0", ":1", ... ":9", ";0", ...
This occurs if the program simply subtracts 1900 from the year
and adds the decade to the US-ASCII character zero.  Programs
wishing to robustly deal with dates generated by such broken
software should detect non-numeric decades and interpret
appropriately.

The problems with two digit years amply demonstrate why all dates and
times used in Internet protocols MUST be fully qualified.

