[[annexC]]
[appendix]
== Leap Seconds

In 1970 CCIR Recommendation 460 produced international agreement that starting on 1972-01-01
radio broadcast time signals should provide SI seconds with
occasional leaps of 1 SI second as necessary to agree with Universal Time.
The time scale in radio broadcasts became known as UTC, and the
current version of that recommendation is <<ITU-R-TF>>.
Since 1988 IERS has the
https://www.iers.org/SharedDocs/Publikationen/EN/IERS/Documents/IERS_Leap_Seconds.pdf?__blob=publicationFile&v=1[responsibility for announcing when leap seconds
will be introduced into UTC].
Further information about leap seconds can be found at the
https://www.usno.navy.mil/USNO/time/master-clock/leap-seconds[US Navy Oceanography Portal].
In particular, it notes that:

[quote]
The decision to introduce a leap second in UTC is the
responsibility of the International Earth Rotation Service <<IERS>>.
According to the CCIR Recommendation, first preference is given to
the opportunities at the end of December and June, and second
preference to those at the end of March and September.

When required, insertion of a leap second occurs as an extra second
at the end of a day in UTC, represented by a timestamp of the form
YYYY-MM-DDT23:59:60Z.  A leap second occurs simultaneously in all
time zones, so that time zone relationships are not affected.  See
section <<date-time-examples>> for some examples of leap second times.

The following table is an excerpt from the table maintained by the
IERS.
The source data are located at the
https://hpiers.obspm.fr/eop-pc/index.php?index=TAI-UTC_tab&lang=en[Earth Orientation Parameters Product Centre at Observatoire de Paris].

For dates after the initial adjustment on 1972-01-01 this table shows the date of the leap second, and the difference
between the time scale TAI (which is not adjusted by leap seconds)
and UTC after that leap second.

.Historic leap seconds
|===
| UTC Date  | TAI - UTC After Leap Second

| 1972-06-30    | 11
| 1972-12-31    | 12
| 1973-12-31    | 13
| 1974-12-31    | 14
| 1975-12-31    | 15
| 1976-12-31    | 16
| 1977-12-31    | 17
| 1978-12-31    | 18
| 1979-12-31    | 19
| 1981-06-30    | 20
| 1982-06-30    | 21
| 1983-06-30    | 22
| 1985-06-30    | 23
| 1987-12-31    | 24
| 1989-12-31    | 25
| 1990-12-31    | 26
| 1992-06-30    | 27
| 1993-06-30    | 28
| 1994-06-30    | 29
| 1995-12-31    | 30
| 1997-06-30    | 31
| 1998-12-31    | 32
| 2005-12-31    | 33
| 2008-12-31    | 34
| 2012-06-30    | 35
| 2015-06-30    | 36
| 2016-12-31    | 37
|===
